[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bird_runner"
version = "0.1.0"
requires-python = ">=3.8"

[dependencies]
sqlalchemy = "^2.0.43"
